name: envirocast
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  kdgaugeview: ^1.0.4
  geolocator: ^10.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sliding_switch: ^1.1.0
  lottie: ^3.1.0
  tab_container: ^2.0.0
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  firebase_database: ^10.5.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter_charts: ^0.5.2
  geocoding: ^2.0.4
  fl_chart: ^0.40.0
  awesome_notifications: ^0.9.3+1
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
